name: Build and test

on:
    push:
        branches: main
    pull_request:

env:
  rust_version: "1.72"
  swift_version: "5.9"

jobs:
  build_fmt_test:
    runs-on: macos-13

    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "${{env.swift_version}}"
    - name: Setup Rust
      run: |
        rustup default "${{env.rust_version}}"
        cargo install cargo-swift
        rustup toolchain install aarch64-apple-darwin
    - name: Check out sources
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build rust bindings (macOS only)
      run: cargo swift package --name=ConcordiumWalletCrypto --platforms=macos --release
      working-directory: ./lib/crypto
    - name: Check formatting
      run: swift package plugin --allow-writing-to-package-directory swiftformat --lint
    - name: Build project
      run: swift build
    #- name: Run tests
    #  run: swift test
