name: Build and test

on:
  push:
    branches: main
  pull_request:

jobs:
  build-fmt-test:
    strategy:
      matrix:
        runner:
        - macos-12 # X64
        - macos-13 # X64
        - macos-14 # ARM64
        include:
        - runner: macos-14
          lint: true


    runs-on: "${{matrix.runner}}"

    steps:
    - name: Check out sources
      uses: actions/checkout@v4
    - name: Check formatting
      if: matrix.lint
      run: swift package plugin --allow-writing-to-package-directory swiftformat ./examples --lint
    - name: Build project and run tests
      run: swift test
    - name: Build example CLI
      working-directory: ./examples/CLI
      run: swift build
    - name: Build DocSnippets examples
      working-directory: ./examples/DocSnippets
      run: swift build
