name: Build and test

on:
    push:
        branches: main
    pull_request:

env:
  swift_version: "5.9"

jobs:
  build_fmt_test:
    runs-on: macos-13

    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "${{ env.swift_version }}"
    - name: Check out sources
      uses: actions/checkout@v4
    - name: Check formatting
      run: swift package plugin --allow-writing-to-package-directory swiftformat --lint
    - name: Build project
      run: swift build
    #- name: Run tests
    #  run: swift test
