name: Build and test

on:
  push:
    branches: main
  pull_request:

jobs:
  build-fmt-test:
    strategy:
      matrix:
        runner:
        - macos-11 # X64
        - macos-12 # X64
        - macos-13 # X64
        - macos-14 # ARM64

    runs-on: "${{matrix.runner}}"

    steps:
    - name: Check out sources
      uses: actions/checkout@v4
    - name: "[Debug]: runner.name (${{runner.name}})"
      run: echo "${{runner.name}}"
    - name: Check formatting (except macOS 11)
      if: runner.name != 'macos-11'
      run: swift package plugin --allow-writing-to-package-directory swiftformat ./examples --lint
    - name: Build project and run tests
      run: swift test
    - name: Build example CLI
      working-directory: ./examples/CLI
      run: swift build
