name: Build and test

on:
    push:
        branches: main
    pull_request:

env:
  swift_version: "5.9"

jobs:
  build-fmt-test:
    strategy:
      matrix:
        runner:
          - macos-11
          - macos-12
          - macos-13
          - macos-14

    runs-on: "${{matrix.runner}}"

    steps:
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "${{env.swift_version}}"
    - name: Check out sources
      uses: actions/checkout@v4
    - name: Check formatting
      run: swift package plugin --allow-writing-to-package-directory swiftformat ./examples --lint
    - name: Build project and run tests
      run: swift test
    - name: Build example CLI
      working-directory: ./examples/CLI
      run: swift build
